
package com.dxss.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "queryservice", targetNamespace = "http://ws.dxss.com/", wsdlLocation = "file:/G:/YCC/queryservice.wsdl")
public class Queryservice
    extends Service
{

    private final static URL QUERYSERVICE_WSDL_LOCATION;
    private final static WebServiceException QUERYSERVICE_EXCEPTION;
    private final static QName QUERYSERVICE_QNAME = new QName("http://ws.dxss.com/", "queryservice");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("queryservice.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        QUERYSERVICE_WSDL_LOCATION = url;
        QUERYSERVICE_EXCEPTION = e;
    }

    public Queryservice() {
        super(__getWsdlLocation(), QUERYSERVICE_QNAME);
    }

    public Queryservice(WebServiceFeature... features) {
        super(__getWsdlLocation(), QUERYSERVICE_QNAME, features);
    }

    public Queryservice(URL wsdlLocation) {
        super(wsdlLocation, QUERYSERVICE_QNAME);
    }

    public Queryservice(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, QUERYSERVICE_QNAME, features);
    }

    public Queryservice(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Queryservice(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns QueryServicePortType
     */
    @WebEndpoint(name = "QueryServiceFor718ImplPort")
    public QueryServicePortType getQueryServiceFor718ImplPort() {
        return super.getPort(new QName("http://ws.dxss.com/", "QueryServiceFor718ImplPort"), QueryServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryServicePortType
     */
    @WebEndpoint(name = "QueryServiceFor718ImplPort")
    public QueryServicePortType getQueryServiceFor718ImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.dxss.com/", "QueryServiceFor718ImplPort"), QueryServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QUERYSERVICE_EXCEPTION!= null) {
            throw QUERYSERVICE_EXCEPTION;
        }
        return QUERYSERVICE_WSDL_LOCATION;
    }

}
